# Generated by Django 5.2.6 on 2025-10-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_user_product_user_stockmovement_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="user",
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
