# Generated by Django 5.2.6 on 2025-10-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_remove_stockmovement_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
