# Generated by Django 5.2.6 on 2025-10-30 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_sale_saleitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("SALE", "Sale"),
                    ("RESTOCK", "Restock"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("IMPORT", "Bulk Import"),
                ],
                default="ADJUSTMENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
